CREATE DATABASE IF NOT EXISTS organstock;
USE organstock;

CREATE TABLE IF NOT EXISTS user (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	country VARCHAR(255) NOT NULL,
	province VARCHAR(255) NOT NULL,
	address VARCHAR(255) NOT NULL,
	physician BIT NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	suffix VARCHAR(255),
	degree VARCHAR(255),
	agency VARCHAR(255) NOT NULL,
	license_num VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS organ (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	seller_id INTEGER NOT NULL REFERENCES user,
	organ_type VARCHAR(255) NOT NULL,
	blood_type VARCHAR(255) NOT NULL,
	weight INTEGER UNSIGNED NOT NULL,
	owner_dob DATE NOT NULL,
	description TEXT,

	FOREIGN KEY (seller_id) REFERENCES user (id),
	INDEX (seller_id)
);

CREATE TABLE IF NOT EXISTS cart (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	user_id INTEGER NOT NULL REFERENCES user,
	organ_id INTEGER NOT NULL REFERENCES organ,

	FOREIGN KEY (user_id) REFERENCES user (id),
	FOREIGN KEY (organ_id) REFERENCES organ (id),
	INDEX (user_id),
	INDEX (organ_id)
);
